//
//  VisitorModel.swift
//  OneTag
//
//  Created by Amr El Shazly on 07/02/2024.
//

protocol Visitor {
    var visitorAddonBalanceUsageInitialActive: String? { get set }
    var visitorAddonBalanceUsageRemainingActive: String? { get set }
    var visitorAddonBalanceUsageTypeActive: String? { get set }
    var visitorAddonDateEndActive: String? { get set }
    var visitorAddonDateStartActive: String? { get set }
    var visitorAddonIdActive: String? { get set }
    var visitorAddonIdList: String? { get set }
    var visitorAddonIdPrimary: String? { get set }
    var visitorAddonNameActiveLocale: String? { get set }
    var visitorAddonNameActive: String? { get set }
    var visitorAddonPackageIdActive: String? { get set }
    var visitorAddonPackageIdList: String? { get set }
    var visitorAddonPackageIdPrimary: String? { get set }
    var visitorAddonRecurrenceTypeActive: String? { get set }
    var visitorAddonStatusActive: String? { get set }
    var visitorAddonTargetSegmentActive: String? { get set }
    var visitorAddonTypeActive: String? { get set }
    var visitorAddons: String? { get set }
    var visitorAssetBalanceCreditActive: String? { get set }
    var visitorAssetBalanceLoyaltyPointsActive: String? { get set }
    var visitorAssetBalanceUsageInitialActive: String? { get set }
    var visitorAssetBalanceUsageRemainingActive: String? { get set }
    var visitorAssetBalanceUsageTypeActive: String? { get set }
    var visitorAssetDateEndActive: String? { get set }
    var visitorAssetDateStartActive: String? { get set }
    var visitorAssetDeviceIdActive: String? { get set }
    var visitorAssetDeviceIdList: String? { get set }
    var visitorAssetDeviceIdPrimary: String? { get set }
    var visitorAssetDeviceNameActive: String? { get set }
    var visitorAssetLocaleActive: String? { get set }
    var visitorAssetPlanDateEndActive: String? { get set }
    var visitorAssetPlanDateStartActive: String? { get set }
    var visitorAssetPlanDurationActive: String? { get set }
    var visitorAssetPlanIdActive: String? { get set }
    var visitorAssetPlanIdList: String? { get set }
    var visitorAssetPlanIdPrimary: String? { get set }
    var visitorAssetPlanNameActiveLocale: String? { get set }
    var visitorAssetPlanNameActive: String? { get set }
    var visitorAssetPlanRemainingActive: String? { get set }
    var visitorAssetPlanTypeActive: String? { get set }
    var visitorAssetStatusActive: String? { get set }
    var visitorAssetTypeActive: String? { get set }
    var visitorAssetUserAgeActive: String? { get set }
    var visitorAssetUserGenderActive: String? { get set }
    var visitorAssetUserNameTitleActive: String? { get set }
    var visitorAssetValueArpuActive: String? { get set }
    var visitorAssetValueMarpuActive: String? { get set }
    var visitorAssetValueRevenueActive: String? { get set }
    var visitorAssetValueSubsidyActive: String? { get set }
    var visitorAssetValueTenureActive: String? { get set }
    var visitorBillDateDuePreviousActive: String? { get set }
    var visitorBillDateInvoiceCurrentActive: String? { get set }
    var visitorBillDateInvoicePreviousActive: String? { get set }
    var visitorBillDirectDebitStatusActive: String? { get set }
    var visitorBillEbillStatusActive: String? { get set }
    var visitorCampaigns: String? { get set }
    var visitorCustomerAccountManagerId: String? { get set }
    var visitorCustomerBalanceCredit: String? { get set }
    var visitorCustomerBalanceLoyaltyPoints: String? { get set }
    var visitorCustomerDateEnd: String? { get set }
    var visitorCustomerDateStart: String? { get set }
    var visitorCustomerGender: String? { get set }
    var visitorCustomerLocale: String? { get set }
    var visitorCustomerLocationCity: String? { get set }
    var visitorCustomerLocationCountry: String? { get set }
    var visitorCustomerLocationId: String? { get set }
    var visitorCustomerLocationRegion: String? { get set }
    var visitorCustomerLocationType: String? { get set }
    var visitorCustomerNameTitle: String? { get set }
    var visitorCustomerOwner: String? { get set }
    var visitorCustomerSegment: String? { get set }
    var visitorCustomerStatus: String? { get set }
    var visitorCustomerType: String? { get set }
    var visitorCustomerValueArpu: String? { get set }
    var visitorCustomerValueMarpu: String? { get set }
    var visitorCustomerValueRevenue: String? { get set }
    var visitorCustomerValueSubsidy: String? { get set }
    var visitorCustomerValueTenure: String? { get set }
    var visitorIdAccountActive: String? { get set }
    var visitorIdAccountList: String? { get set }
    var visitorIdAccountPrimary: String? { get set }
    var visitorIdAecid: String? { get set }
    var visitorIdAnonymous: String? { get set }
    var visitorIdAssetActive: String? { get set }
    var visitorIdAssetList: String? { get set }
    var visitorIdAssetPrimary: String? { get set }
    var visitorIdBillActive: String? { get set }
    var visitorIdBillList: String? { get set }
    var visitorIdBillPrimary: String? { get set }
    var visitorIdClickAdvertising: String? { get set }
    var visitorIdCms: String? { get set }
}
